# Generated by Django 4.1 on 2022-11-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schcontactapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolcontact',
            name='date',
        ),
    ]
